### PR TITLE
tests: Add test case for cross-organization subwf

### LINKED ISSUE #2: Add test case for subworkflow with different module remotes
Add a new test case under [subworkflows/install](https://github.com/sanger-tol/nf-core-tools/blob/master/tests/subworkflows/install.py) that attempts to download a subworkflow with cross-repository modules, so as to have an automated and clear functionality goal. This should be done prior to work on the actual implementation.

### PR DESCRIPTION
**Pull request by jvfe**
Strangely it is passing at the moment, it seems the install command returns a passing exit code regardless of installing all modules.

- Addresses sanger-tol/nf-core-tools#2

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by muffato** [comment]
You mean it's passing locally ? I can't see any action run here on GitHub CI

**Comment by muffato** [comment]
Ah, that's because Actions are turned off by default on forked repositories.
Screenshot 2024-06-25 at 11 42 37

I've now enabled them, but probably they will only kick in next time there's a commit on this branch.

**Comment by jvfe** [comment]
> Ah, that's because Actions are turned off by default on forked repositories.

Ooh ok that makes sense, I had tested it locally.
Either way, I just manually submitted the action and it does show what I said: https://github.com/sanger-tol/nf-core-tools/actions/runs/9661393766/job/26649018814
Another test failed (not related to my changes, it's just changelog/bump issues), but mine succeeds. 

I'll test the actual subworkflow install command manually (outside of the test) and capture the exit code, but that seems like it's returning a 0 even when it doesn't install every component.

**Comment by jvfe** [comment]
Yep, that's definitely the case, when running:

```bash
nf-core subworkflows --git-remote https://github.com/jvfe/test-subworkflow-remote install hic_bwamem2
```

and then getting the exit code:

```bash
echo $?
```

it returns 0.

**Comment by jvfe** [comment]
> Yep, that's definitely the case, when running:
> 
> ```shell
> nf-core subworkflows --git-remote https://github.com/jvfe/test-subworkflow-remote install hic_bwamem2
> ```
> 
> and then getting the exit code:
> 
> ```shell
> echo $?
> ```
> 
> it returns 0.

Apparently this is expected (discussed [here](https://nfcore.slack.com/archives/CE5LG7WMB/p1719404967888529)). So the way to go is to check for the missing module in the module json list, which is what [568363a](https://github.com/sanger-tol/nf-core-tools/pull/6/commits/568363a4b025d6bdfbce031a12e9898df3ca0137) does.

**Comment by jvfe** [comment]
Yep, now it's failing as expected: https://github.com/sanger-tol/nf-core-tools/actions/runs/9717099844/job/26822060543
For some reason the actions are not running automatically, I'll check this later.

**Comment by muffato** [comment]
Looks fine.

> Yep, now it's failing as expected: https://github.com/sanger-tol/nf-core-tools/actions/runs/9717099844/job/26822060543 For some reason the actions are not running automatically, I'll check this later.

Yep, I'm wondering too !

Also, if the return value of `install(...)` is not an indicator of success/failure, why is it checked in other parts of `tests/subworkflows/install.py` ? If something's indeed not right, make it an issue on the nf-core repo.

**Comment by jvfe** [comment]
> Looks fine.
> 
> > Yep, now it's failing as expected: https://github.com/sanger-tol/nf-core-tools/actions/runs/9717099844/job/26822060543 For some reason the actions are not running automatically, I'll check this later.
> 
> Yep, I'm wondering too !
> 
> Also, if the return value of `install(...)` is not an indicator of success/failure, why is it checked in other parts of `tests/subworkflows/install.py` ? If something's indeed not right, make it an issue on the nf-core repo.

Thanks! I've now created the issue. I was hesitant to create it at first since given the conversation on slack I thought it was something expected.

Yeah and I'm not sure why the CI wasn't running, but I just sent some dummy commits and now it runs. I tried to change the base branch for this PR to see if that was the reason behind it (like if maybe it just runs the CI for PRs against the main branch), but apparently not.

**Comment by jvfe** [comment]
Apparently the issue with the modules test failing is unrelated to my changes, because, after some local testing, I could see it also fails in the master branch. Given that's the case, I'll be merging this then.

**Pull request merged**
